### PR TITLE
Optimize VNC screen update to reduce delays

### LINKED ISSUE #81: Rendering delay in VNC backend
I observed a rendering delay when running the VNC backend on the Raspberry Pi 3B.

https://github.com/user-attachments/assets/2fc7fea0-b274-47ef-97ff-cde600655bce

### PR DESCRIPTION
**Pull request by ndsl7109256**
Previously, the VNC renderer fed the damaged region to the buffer line by line, resulting in significant rendering delays due to frequent buffer updates.

The implementation has been optimized to aggregate all updates during the current screen refresh cycle. The buffer is now updated once per refresh with the complete damaged region, reducing rendering delays and preventing screen tearing.

## Previously

https://github.com/user-attachments/assets/2397db3d-a4c4-4cd6-818c-03435c5f0d89

## After optimizing

https://github.com/user-attachments/assets/d6619129-8d06-4f99-8337-46776247206f

## Comparing
The table compares the performance of screen updating measuring with GIFs with significant vertical variations(Selected to better illustrate the delay caused by line-by-line buffer updates) ,  before and after optimization, measured in average execution time (ms). Numbers in parentheses represent the standard deviation (std).
| GIF size |       Before        |       After       |
|:--------:|:-------------------:|:-----------------:|
| 128x128  |  4.049ms(3.363ms)   | 1.928ms(1.424 ms) |
| 256x256  | 15.797ms(11.030ms)  | 2.196ms(1.064 ms) |
| 512x512  | 52.259ms(30.524 ms) | 2.379ms(1.138 ms) |

Close #81

### CODE REVIEW

**Comment by jserv** [comment]
Thank @ndsl7109256 for contributing!

**Comment by huaxinliao** [comment]
I am curious whether the experimental data in [Comparing](https://github.com/sysprog21/mado/pull/84#issue-2757485665) was generated with the assistance of other tools.

**Comment by ndsl7109256** [comment]
I first used `gprof` to check the hotspot of the VNC backend and found that `_twin_vnc_work` takes a significant amount of time.
```
  %   cumulative   self              self     total           
time   seconds   seconds    calls   s/call   s/call  name    
18.83      0.84     0.84 197545969     0.00     0.00  _twin_run_timeout
17.04      1.60     0.76 395091937     0.00     0.00  _twin_queue_review_order
12.33      2.15     0.55 197545969     0.00     0.00  _twin_vnc_work
```
Then, I measure how long `_twin_vnc_work` takes directly using 10-second samples.
```diff
+ clock_t start = clock();
twin_screen_t *screen = SCREEN(closure);
if (twin_screen_damaged(screen))
    twin_screen_update(screen);
+ clock_t end = clock();
```

**Comment by jserv** [comment]
> I first used `gprof` to check the hotspot of the VNC backend and found that `_twin_vnc_work` takes a significant amount of time. Then, I measure how long `_twin_vnc_work` takes directly using 10-second samples.

[uftrace](https://github.com/namhyung/uftrace) is useful, tool.

**Pull request merged**
