### PR TITLE
move private header file to src

### PR DESCRIPTION
**Pull request by Damien-Chen**
Move "twin_private.h" to src folder, and make a new "util.h" header file that include necessary header file for the expansion of future use.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
The header `twin_private.h` is used internally, and don't create any header referring to it. See #9

**Comment by Damien-Chen** [comment]
Basd on my understanding, so we can directory include `twin_private.h` in source code, but indirectory include is no need right ? (based on my change, I create `util.h` include `twin_private.h`)

**Comment by jserv** [comment]
> Based on my understanding, so we can directory include `twin_private.h` in source code, but indirectory include is no need right ?

The `include` directory should contain `twin.h` as the public header and nothing more, meaning that the current `twin_private.h` is a hack to allow the building of some applications invoking the internal functions. You can proceed with issue #9 to contribute to this project.

**Comment by jserv** [comment]
Close to concentrate on #9

**Pull request closed without merging**
